### ISSUE TITLE
Conformité YAML lors de la génération depuis un sitemap

### ISSUE THREAD

**Issue by aw73** [cnumr/GreenIT-Analysis-cli#12]
Lorsqu'on utilise la commande `greenit parseSitemap <sitemap_url> <yaml_output_file>` le fichier YAML résultant n'est pas conforme.

Il est sous la forme :

```yaml
- url1
- url2
- url3
```
Avec ce fichier la commande `greenit analyse` ne fonctionne pas.

Si manuellement je transforme ce fichier en :

```yaml
- url: "url1"
- url: "url2"
- url: "url3"
```
Dans cette version tout fonctionne parfaitement.

**Comment by jpreisner** [comment]
Bonjour @aw73, merci pour la création de cette issue. J'ai créé un correctif, j'attends que la PR soit validée.

Le fichier généré aura ce format : 
```yaml
- url: url1
- url: url2
- url: url3
```
Le fait qu'il n'y ait pas les simples ou doubles quotes autour des urls n'est pas un problème. Le yaml est conforme et l'analyse fonctionne.
