### ISSUE TITLE
Cliquer sur un élément dans un iFrame

### ISSUE THREAD

**Issue by benel** [cnumr/GreenIT-Analysis-cli#81]
Bonjour,

Certains scénarios nécessitent de cliquer sur des boutons dans un iframe. Comment fait-on ?

J'essaie par exemple d'évaluer l'impact de la lecture des quotidiens nationaux. Pour les quotidiens que j'ai testés jusqu'à maintenant j'y arrive mais je rencontre une difficulté avec le bouton de consentement du Figaro. 

Voici ce que cela pourrait donner pour la consultation d'un article : 

```yaml
- name: Le Figaro – Actualités
  url: https://www.lefigaro.fr
  waitForSelector: iframe[title="Fenêtre de consentement"]
  actions:
    - name: Refuser d'être suivi
      type: click
      element: button[aria-label="ACCEPTER ET CONTINUER la collecte de vos données"]
      screenshot: cookie.png
    - name: Consulter les titres
      type: scroll
    - name: Choisir un article
      type: click
      element: 'section:nth-of-type(1) > article > a'
      pageChange: true
      waitForSelector: .fig-paragraph
      screenshot: article1.png
    - name: Lire l'article
      type: scroll
```

J'ai essayé plusieurs sélecteurs (sur le texte, l'aria-label, en le préfixant ou non avec l'iframe) mais j'ai toujours un `Error: No element found for selector`. 

Avez-vous rencontré ce genre de cas ? Si oui, comment l'avez-vous résolu ?

Merci d'avance.
